export interface ScholarisFact {
  header: string;
  subtext: string;
}

export const SCHOLARIS_FACTS: ScholarisFact[] = [
  // --- Probability / Exam Overlap Facts ---
  {
    header: "7 in 12 exam questions have appeared on Scholaris.",
    subtext:
      "Our AI extracts questions directly from your current NSUK lecture materials — the same materials your lecturers set exams from. The overlap is not a coincidence.",
  },
  {
    header: "You've already seen this question before.",
    subtext:
      "Scholaris generates 100 high-quality questions per course from your actual lecture content. Statistically, practicing all of them puts you ahead of 80% of your class.",
  },
  {
    header: "Your CBT exam has 40–50 questions. Scholaris gives you 100.",
    subtext:
      "That means you're practicing at 2× the exam volume — which means when you sit down for the real thing, nothing should surprise you.",
  },
  {
    header: "The questions aren't random. They're extracted from your notes.",
    subtext:
      "Every question on Scholaris was generated by AI trained on the exact lecture materials uploaded for your course. If it's in your notes, it's likely in our bank.",
  },
  {
    header: "Students who complete all 100 questions are 3× more prepared.",
    subtext:
      "Finishing the full Scholaris question bank before your CBT dramatically increases your familiarity with question patterns, phrasing, and topic weight.",
  },

  // --- Performance / Weak Area Facts ---
  {
    header: "Scholaris knows where you'll lose marks.",
    subtext:
      "Your performance dashboard tracks which topics you're consistently getting wrong — so you can focus your revision where it actually matters, not where you feel comfortable.",
  },
  {
    header: "Most students fail on the same 20% of topics.",
    subtext:
      "Scholaris identifies your weak areas after every session and surfaces them first. Fix the 20%, and you protect the bulk of your score.",
  },
  {
    header: "Confidence isn't the same as readiness.",
    subtext:
      "Many students feel ready but haven't tested themselves under real conditions. Scholaris's ranked sessions simulate exam pressure so your brain practices performing, not just remembering.",
  },

  // --- Study / CBT Facts ---
  {
    header: "CBT punishes guessing. Scholaris trains you not to.",
    subtext:
      "Multiple-choice exams reward pattern recognition. The more questions you practice, the faster your brain identifies the right option — even under time pressure.",
  },
  {
    header: "Reading alone is not enough for CBT.",
    subtext:
      "Studies show active recall — answering questions — improves retention by up to 50% compared to passive reading. Scholaris is built entirely around that principle.",
  },
  {
    header: "Your brain forgets 70% of what you read within 24 hours.",
    subtext:
      "The Ebbinghaus Forgetting Curve shows knowledge decays fast without practice. Scholaris's repeated questioning keeps your memory sharp right up to exam day.",
  },
  {
    header: "The best time to practice was yesterday. The second best time is now.",
    subtext:
      "Students who start practicing at least 3 days before their CBT consistently outperform those who cram the night before. Start a session today.",
  },

  // --- Scholaris Platform Facts ---
  {
    header: "AI studied your course so you study smarter.",
    subtext:
      "Scholaris's AI doesn't generate generic questions — it reads your NSUK lecture materials and extracts the most exam-relevant content, ranked by topic coverage.",
  },
  {
    header: "Every session on Scholaris is a ranked session.",
    subtext:
      "Your results are tracked, scored, and synced to the cloud after every exam. Your improvement over time is visible — and so are the gaps you still need to close.",
  },
  {
    header: "You're not just preparing. You're optimizing.",
    subtext:
      "Scholaris doesn't just give you questions — it shows you where your time is best spent, which courses need attention, and how your performance trends over time.",
  },
];